on:
    push:
        branches:
            - master
name: Test
jobs:
    Test-Action:
        name: Test-Action
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Add HTTP basic auth credentials
              run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > ./app/auth.json

            - name: composer install
              if: steps.cache.outputs.cache-hit != 'true'
              run: composer install
              working-directory: ./
              run: composer test
